
CREATE TABLE tbl_access_token (
  userid VARCHAR2(50) NOT NULL,
  token VARCHAR2(50) PRIMARY KEY,
  expired DATE DEFAULT SYSDATE + 3 NOT NULL,
  logon DATE DEFAULT SYSDATE NOT NULL,
  registdate DATE DEFAULT SYSDATE NOT NULL,
  updatedate DATE DEFAULT SYSDATE NOT NULL
);